### ISSUE TITLE
How to build with stm32cube?

### ISSUE THREAD

**Issue by afaber999** [waveplate/tcd1304ap-stm32-ccdview#1]
How can I build the firmware with the stm32 cube IDE? Could you include some instructions in the readme.md files since I don't see any stm32 cube ide project related files

**Comment by waveplate** [comment]
hey, thanks for the feedback. i had neglected to commit the following project files:

`.project`
`.cproject`
`.mxproject`
`.settings/`

i think you should be able to open the `.project` file with STM32CubeIDE -- let me know how it goes.

**Comment by SAMBizzCom** [comment]
It is a wonderful project. I really appreciate it. I want to get benefit from it but...…I want to use it on STM32F411. Can you please update this project for STM32F411. It will help me a lot... please please please.
Please provide *.ioc file of this project. 
I am unable to open this project in CubeIDE

**Comment by waveplate** [comment]
hey, sorry for the delay! in the interest of helping you out, i've ordered some STM32F411CEU6 development boards. i'll get everything up and running on this new dev board and keep you posted.

i assume you haven't already gotten the project up and running?

**Comment by waveplate** [comment]
@SAMBizzCom you can find the project files including the .ioc file in the `stm32f411ceu6` branch. do not actually generate code from the .ioc file however, as it will overwrite the code. just clone the repo, check out the `stm32f411ceu6` branch, then import the directory into STM32CubeIDE. then you should be able to build it and upload it to your board
